# SFT Training with Qwen3-8B
# python -m apps.sft.main --config apps/sft/qwen3_8b.yaml

comm:
  trace_buf_size: 0
  init_timeout_seconds: 1800

model_name: "Qwen/Qwen3-8B"

model:
  name: qwen3
  flavor: 8B
  hf_assets_path: hf://${model_name}

provisioner:
  launcher: slurm
  job_name: sft_qwen3_8b
  slurm_args:
    account: AIFAC_L07_016
    qos: qos_llm_min
    partition: boost_usr_prod
  mem: 0
  cpus_per_task: 32
  gpus_per_node: 4

optimizer:
  name: AdamW
  lr: 1e-5
  eps: 1e-8

lr_scheduler:
  warmup_steps: 200

training:
  local_batch_size: 1
  seq_len: 1024
  max_norm: 1.0
  steps: 1000
  compile: false
  dtype: bfloat16
  gc_freq: 1
  dataset:
    - path: "/leonardo_scratch/fast/iGen_train/datasets/alpaca-cleaned"
      split: "train[:95%]"

eval:
  eval_every_n_steps: 1000
  max_eval_steps: null
  dataset:
    - path: "/leonardo_scratch/fast/iGen_train/datasets/alpaca-cleaned"
      split: "train[95%:]"

parallelism:
  data_parallel_replicate_degree: 1
  data_parallel_shard_degree: 4
  tensor_parallel_degree: 1
  pipeline_parallel_degree: 1
  context_parallel_degree: 1
  expert_parallel_degree: 1
  disable_loss_parallel: false

checkpoint:
  enable: true
  folder: ./checkpoint
  initial_load_path: hf://${model_name}
  initial_load_in_hf: true
  last_save_in_hf: true
  last_save_model_only: false
  interval: 50
  async_mode: "disabled"

activation_checkpoint:
  mode: selective
  selective_ac_option: op

metric_logging:
  wandb:
    project: sft-training
    group: sft_exp_${oc.env:USER}
    logging_mode: global_reduce
  console:
    logging_mode: global_reduce


services: {}

actors:
  sft_trainer:
    procs: 4
    hosts: 1
    with_gpus: true
    mesh_name: sft_trainer